// Amiri Regular Arabic Font - Base64 encoded (subset for better performance)
// This is a minimal subset of Amiri font for Arabic text support
// Full font source: https://fonts.google.com/specimen/Amiri

export const amiriRegularBase64 = `AAEAAAASAQAABAAgR0RFRgBjAAYAABxUAAAALkdQT1MGBQEaAAAcjAAAA9xHU1VCkw2CAgAAIGgAAAA0T1MvMnZsASoAAAG4AAAAYGNtYXAADwH9AAADGAAAAWRnYXNw//8AAwAAHEwAAAAIZ2x5Zg7fB4cAAASUAAAUnGhlYWQh7TW5AAAA7AAAADZoaGVhB+EEdAAAASwAAAAkaG10eE5eApcAAAIYAAABBGxvY2Fjb2NvYwAABHwAAAA2bWF4cABqAFoAAAFQAAAAIG5hbWVjvjHxAAAZMAAAAnJwb3N0/58AMgAAG6QAAAGoAAEAAAABAAAotP8zXw889QALA+gAAAAA3gJvFgAAAADeAm8WAAD/4APoA0gAAAAIAAIAAAAAAAAAAQAAA0j/MAAgBEwAAAAAAAPoAAEAAAAAAAAAAAAAAAAAAAABAAEAAABFADgABQAAAAAAAgAAAAoACgAAAP8AAAAAAAAAAQQEAZAABQAAAokCzAAAAI8CiQLMAAAB6wAyAQgAAAIABQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGZFZABAAHjh3wNI/zAAXANIAGQAAAABAAAAAAAABAAAAAPpAAAEDAAABAwAAAPcAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAACWAAAAlgAAAJYAAAAAAAAAwAAAAMAAAAcAAEAAAAAAF4AAwABAAAAHAAEAEIAAAAMAAIABgAAAAEAaABzAOHf////+//9AAAAAAB4AHMAeP////j//QABAAAAAAAAAAAAAAEGAAABAAAAAAAAAAECAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCAsEDQUOBg8HEAgRCRIKEwsTDBQNFQ4WDxcQGBEZEhkTGhQbFRwWHRceGB8ZIBohGyIcIx0kHiUfJiAnIShCKSgqKSsrLCwtLC4tLy4wLzEwMjEzMjMyNDQ1NTY1Nzc3ODk6OTo7PDw8Pj09Pz5AP0BBQkJCQ0RFRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAA=`;

export const loadArabicFont = async (doc: any) => {
  doc.addFileToVFS('Arial.ttf', amiriRegularBase64);
  doc.addFont('Arial.ttf', 'Arial', 'normal');
  doc.setFont('Arial');
};

// Alternative - using online Google Fonts (requires internet)
export const getAmiriFontFromGoogle = async (): Promise<string> => {
  try {
    const response = await fetch('https://fonts.gstatic.com/s/amiri/v27/J7aRnpd8CGxBHqUpvrIw74NL.woff2');
    const buffer = await response.arrayBuffer();
    const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)));
    return base64;
  } catch (error) {
    console.error('Failed to load Amiri font:', error);
    return amiriRegularBase64; // Fallback to embedded font
  }
};

// Cairo font as alternative (better for some Arabic styles)
export const cairoFontUrl = 'https://fonts.gstatic.com/s/cairo/v28/SLXgc1nY6HkvangtZmpQdkhzfH5lkSs2SgRjCAGMQ1z0hGA-W1ToLQ-HmkA.woff2';

// Function to add Arabic font to jsPDF
export const addArabicFontToPDF = (doc: any, fontName: string = 'Amiri') => {
  // Using the embedded base64 font
  doc.addFileToVFS(`${fontName}-Regular.ttf`, amiriRegularBase64);
  doc.addFont(`${fontName}-Regular.ttf`, fontName, 'normal');
  doc.setFont(fontName);
};

// Helper to check if text contains Arabic characters
export const hasArabicText = (text: string): boolean => {
  const arabicRegex = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/;
  return arabicRegex.test(text);
};

// Fix Arabic text display (reverse for correct RTL rendering in jsPDF)
export const fixArabicText = (text: string): string => {
  if (!text) return '';

  // If text contains Arabic, we might need to reverse it for correct display
  // jsPDF doesn't natively support RTL, so we handle it manually
  if (hasArabicText(text)) {
    // Split by words and reverse for RTL display
    return text.split(' ').reverse().join(' ');
  }

  return text;
};
