// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inpaclmiokjwgjkdslhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucGFjbG1pb2tqd2dqa2RzbGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTA2MTMsImV4cCI6MjA3NDcyNjYxM30.B_p08WJeGoGQx4NCUUmD3099xXoOomIPkYcViN7dC7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});